### ISSUE TITLE
Allow certain existing features to be optional

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#34]
- [x] Turn instant replay into a toggle. Buggy feature, not everyone may want it.
- [x] Turn "DetectPerpetrator" into a toggle. Some people may not want overly-aggressive cops.
- [x] Turn Discord Rich Presence into a toggle. Privacy, amiright?

**Comment by Deebz96** [comment]
Perhaps command line arguments could be toggleable/configurable in the INI too? Things like borderless, heapsize, nopause, and even the default commands like nomovie and nolockcheck would be nice to have in there.

This is mainly so that we can start the game via gameranger, or directly from the exe without needing to worry about commands not being passed.

**Comment by Deebz96** [comment]
Now include the random seed feature as an INI toggle.
