### ISSUE TITLE
Fix bugs related to particles

### ISSUE THREAD

**Issue by Fireboyd78** [Fireboyd78/mm2hook#49]
- [x] Fix particles not showing up in the rear-view mirror.
- [x] Fix particles not showing up when in the pause menu.

**Comment by Deebz96** [comment]
Note: Rain is included in particles that don't show up in the mirror. However, it still shows up when paused.

**Comment by Dummiesman** [comment]
This issue is not related to particles per se.

`dgPhysEntity` registers a drawable in a PostUpdate. This is done on vehCar, and banger objects. Drawables do not show up in the rear view mirror, and since physics are paused when the game is paused, PostUpdate never is called during game pause, therefore no drawables get rendered.

**Comment by Dummiesman** [comment]
Fixed particles not rendering when paused by removing callback clearing. Since in the paused state, callbacks are not being registered, and therefore have no need to be cleared.

See commit e85ad4b8e1b75df94f7594ab3e2cb13829687cd1
