### ISSUE TITLE
Fix bugs related to trailers

### ISSUE THREAD

**Issue by Deebz96** [Fireboyd78/mm2hook#53]
- [ ] Fix `TWHL3` object always steering with a SteeringLimit value of `0.45`, despite settings in tuning files.

- [x] Fix `TLIGHT` object not appearing in the game, despite being present in the model.

As for the `TWHL3` object issue, Aaron suspected that it may be related to that object not being properly initialized. I am 99% sure that 0.45 is the default steering value applied if the vehicle/trailer does not have a tuning file. So it's possible that this wheel is not getting info from the tuning file.

Should be noted that I can work around this issue in RV6 by making the other wheel also steer at 45 degrees. The fire truck's trailer in the real world can steer just like that. However, I would ideally like to reduce how much it steers, and have tail lights working too of course.

**Comment by Deebz96** [comment]
As for the `TWHL3` object issue, Aaron suspected that it may be related to that object not being properly initialized. I am 99% sure that 0.45 is the default steering value applied if the vehicle/trailer does not have a tuning file. So it's possible that this wheel is not getting info from the tuning file.

**Comment by Dummiesman** [comment]
Trailers don't even have a DrawGlow implemented, it never even tries to draw the TLIGHT D: 

Will have to figure out how to grab geometry from the current levelInstance and draw it ourselves.

**Comment by Dummiesman** [comment]
Trailers were looking for `default.dgTrailerJoint` during the Load stage, which is nonexistant in retail. I removed this since if this file was not found, the wheels, which are unrelated to the `dgTrailerJoint`, would not be loaded. 

The actual proper `dgTrailerJoint` gets loaded later on.

I removed the call to `dgTrailerJoint::Load` since `dgTrailerJoint` has defaults anyways.
